### ISSUE TITLE
How to pretrain in a new dataset?

### ISSUE THREAD

**Issue by zhang-zhen-project** [HKUDS/GPT-ST#3]
Dear author,

Thank you for open-sourcing this very meaningful work. I have a couple of questions, and I would appreciate it if you could provide some clarification:

Is GPT-ST only applicable to the four transportation datasets mentioned in your paper? Can I modify certain parameters and run it on other datasets after converting them into time and spatial feature files?

In your project introduction document, I noticed that you employ different running modes and baseline models. Is this a fixed combination? For instance, if I want to use the STGCN baseline model to pre-train my own spatiotemporal dataset, is it feasible?

Thank you very much for your response!

**Comment by LZH-YS1998** [comment]
Hello, thank you for recognizing our work. 
GPT-ST can be applied to various spatiotemporal datasets. If you want to use it on a new dataset, I recommend retraining on it. Here is a brief summary of the steps: you can start by adding the new data file in the ./data folder and include data processing code in ./lib/load_dataset.py, then add a configuration file for the new dataset in ./conf/GPTST_pretrain/.

```
# Use the following command for pretraining, and the path to save the weights is specified in the configuration file of the new dataset.
python Run.py -dataset [new_dataset_name] -mode pretrain

# After completing the pretraining you can proceed with testing. Don't forget to add the conf file for the downstream model and the adjacency matrices required by different baselines:
python Run.py -dataset [new_dataset_name] -mode eval -model STGCN
```

The document only presents a subset of examples, and these are not fixed combinations. If you want to solely pretrain and test the STGCN without utilizing the GPT-ST model for enhancement:

```
python Run.py -dataset [new dataset name] -mode ori -model STGCN
```

You can set debug to True in ./conf/GPTST_pretrain/params_predictors.conf. This will ensure that the STGCN weights are saved.
